version: "3.8"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  ingestion:
    build:
      context: .
      dockerfile: src/data/Dockerfile
    container_name: ingestion_service
    volumes:
      - ./data/raw:/app/data/raw
      - ./.dvc:/app/.dvc
      - ./.git:/app/.git
    command: ["dvc", "repro", "one_hot_encode_labels"]

  training:
    build:
      context: .
      dockerfile: src/models/Dockerfile
    container_name: training_service
    depends_on:
      - ingestion
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./.dvc:/app/.dvc
      - ./.git:/app/.git
    command: ["sh", "-c", "dvc repro --downstream setup_callbacks"]

  prediction:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    container_name: prediction_service
    depends_on:
      - training
    ports:
      - "8000:8000"
    # Mount the Prometheus metrics directory for local testing (optional)
    volumes:
      - ./src/api:/app/src/api

  prometheus:
    image: prom/prometheus
    container_name: prometheus_service
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana
    container_name: grafana_service
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
