stages:
  extract_data:
    cmd: python src/data/extract_raw_data.py
    deps:
    - data/raw/raw_data.tar.gz
    - src/data/extract_raw_data.py
    outs:
    - data/raw/raw_data/data
  load_dataset:
    cmd: python src/data/load_dataset.py
    deps:
    - data/raw/raw_data/data
    - src/data/load_dataset.py
    outs:
    - data/raw/words.csv
  filter_data:
    cmd: python src/data/filter_data.py
    deps:
    - data/raw/words.csv
    - src/data/filter_data.py
    outs:
    - data/processed/filtered_data.csv
  clean_data:
    cmd: python src/data/clean_data.py
    deps:
    - data/processed/filtered_data.csv
    - src/data/clean_data.py
    outs:
    - data/processed/cleaned_data.csv
  encode_data:
    cmd: python src/data/encode_data.py
    deps:
    - data/processed/cleaned_data.csv
    - src/data/encode_data.py
    outs:
    - data/processed/encoded_data.csv
  prepare_features:
    cmd: python src/data/prepare_features.py
    deps:
    - src/data/prepare_features.py
    - data/processed/encoded_data.csv
    outs:
    - data/processed/features.npy
    - data/processed/labels.npy
  split_data:
    cmd: python src/data/split_data.py
    deps:
    - src/data/split_data.py
    - data/processed/features.npy
    - data/processed/labels.npy
    outs:
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    - data/processed/Y_train.npy
    - data/processed/Y_test.npy
  reshape_data:
    cmd: python src/data/reshape_data.py
    deps:
    - src/data/reshape_data.py
    - data/processed/X_train.npy
    - data/processed/X_test.npy
    outs:
    - data/processed/X_train_reshaped.npy
    - data/processed/X_test_reshaped.npy
  calculate_class_weights:
    cmd: python src/data/calculate_class_weights.py
    deps:
    - src/data/calculate_class_weights.py
    - data/processed/Y_train.npy
    outs:
    - data/processed/class_weights.npy
  one_hot_encode_labels:
    cmd: python src/data/one_hot_encode_labels.py
    deps:
    - src/data/one_hot_encode_labels.py
    - data/processed/Y_train.npy
    - data/processed/Y_test.npy
    outs:
    - data/processed/y_train_one_hot.npy
    - data/processed/y_test_one_hot.npy
#  data_augmentation:
#    cmd: python src/data/data_augmentation.py
#    deps:
#      - src/data/data_augmentation.py
#      - data/processed/X_train.npy
#      - data/processed/y_train_one_hot.npy
#      - data/processed/X_test.npy
#      - data/processed/y_test_one_hot.npy
#    outs:
#      - data/processed/train_augmented.npy
#      - data/processed/test_augmented.npy
  setup_callbacks:
    cmd: python src/models/setup_callbacks.py
    deps:
      - src/models/setup_callbacks.py
    outs:
      - models/callbacks.keras

  build_train_cnn:
    cmd: python src/models/build_train_cnn.py
    deps:
      - src/models/build_train_cnn.py
      - models/callbacks.keras
      - data/processed/X_train_reshaped.npy
      - data/processed/y_train_one_hot.npy
      - data/processed/X_test_reshaped.npy
      - data/processed/y_test_one_hot.npy
      - data/processed/class_weights.npy
    outs:
      - models/CNN.keras
      - models/model_architecture_summary.txt
    # metrics:
    #   - metrics/training_history.csv
    plots:
      - metrics/training_accuracy.png
  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - models/CNN.keras
      - data/processed/X_test_reshaped.npy
      - data/processed/y_test_one_hot.npy
    # metrics:
    #   - metrics/classification_report.csv
    #   - metrics/confusion_matrix.csv
    plots:
      - metrics/confusion_matrix.png