stages:
  extract_data:
    cmd: python src/data/extract_raw_data.py
    deps:
    - data/raw/raw_data.tar.gz
    - src/data/extract_raw_data.py
    outs:
    - data/raw/raw_data/data
  load_dataset:
    cmd: python src/data/load_dataset.py
    deps:
    - data/raw/raw_data/data
    - src/data/load_dataset.py
    outs:
    - data/raw/words.csv
  filter_data:
    cmd: python src/data/filter_data.py
    deps:
    - data/raw/words.csv
    - src/data/filter_data.py
    outs:
    - data/processed/filtered_data.csv
