# Dockerfile-training

# Use the official Python base image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy the Python scripts from src/data
COPY src/models/*.py ./src/models/

# Copy the requirements file
COPY src/models/requirements.txt ./requirements.txt

# Copy necessary files from the root directory
COPY dvc.yaml ./
COPY dvc.lock ./          
COPY .gitignore ./        
COPY .dvcignore ./
COPY metrics/ ./metrics/        


# Install required system packages and Python dependencies in a single RUN command
RUN apt-get update && \
    apt-get install -y git && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Expose the port that the FastAPI app will run on (8100)
EXPOSE 8200

# Run the training FastAPI app using uvicorn
CMD ["uvicorn", "src.models.training:app", "--host", "0.0.0.0", "--port", "8200"]