name: CI Tests

on:
  push:
    branches:
      - "**" # Trigger on all branches
  pull_request:
    branches:
      - "**" # Trigger on all pull requests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify Python 3.11

      - name: Install DVC and dependencies
        run: |
          pip install dvc
          pip install -r requirements.txt  # Install other dependencies

      - name: Pull DVC data
        run: |
          dvc pull --force  # Force pull the data tracked by DVC

      - name: Run Tests
        run: |
          python -m unittest discover -s tests -p '*.py'  # Adjust this command based on your test framework
