name: CI Tests

on:
  push:
    branches:
      - "**" # Trigger on all branches
  pull_request:
    branches:
      - "**" # Trigger on all pull requests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t test_service -f tests/Dockerfile .

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/data:/app/data \
            -v ${{ github.workspace }}/models:/app/models \
            -v ${{ github.workspace }}/metrics:/app/metrics \
            -v ${{ github.workspace }}/tests:/app/tests \
            -v ${{ github.workspace }}/.dvc:/app/.dvc \
            -v ${{ github.workspace }}/.git:/app/.git \
            test_service python -m unittest discover -s /app/tests -p '*.py'
